name: publish

on:
  workflow_dispatch:


jobs:
  prediction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: dist

      - name: move files
        run: mv dist/* . && ls

      - name: Commit result back to repo
        continue-on-error: true
        run: |
          git config --global user.name 'The Octocat'
          git config --global user.email 'octocat@github.com'
          git checkout pages 
          git add .
          git commit -m "Updated Results And Predictions"
          git push origin pages -f